name: ecological_footprint_prediction
services:
  streamlit:
    build: .
    image: elfarahma/ml_process_streamlit
    container_name: streamlit_frontend
    depends_on:
      - api
    ports:
      - 8000:8000
    volumes:
      - ./:/home/
  api:
    build: .
    image: elfarahma/ml_process_api
    container_name: api_backend
    ports:
      - 8000:8000
    volumes:
      - ./:/home/
